services:
  - type: web
    name: hostel-meal-app
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
    staticSite:
      source: dist
